// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCks7BKHsleGnaonr8X9Jol5Hk_Gqi7XbU',
    appId: '1:541838238652:web:4290adf8db8fd1024e81b9',
    messagingSenderId: '541838238652',
    projectId: 'cinefavorite-93f7b',
    authDomain: 'cinefavorite-93f7b.firebaseapp.com',
    storageBucket: 'cinefavorite-93f7b.firebasestorage.app',
    measurementId: 'G-N2035C36GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB0EGmkB1BG7MFUYafGodSuTlC-eAMUV0',
    appId: '1:541838238652:android:0587ab460667880c4e81b9',
    messagingSenderId: '541838238652',
    projectId: 'cinefavorite-93f7b',
    storageBucket: 'cinefavorite-93f7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-WZLRz4Mw5Eh42QJFG-NmiOIe6kn72bw',
    appId: '1:541838238652:ios:4ec3d80933232e5a4e81b9',
    messagingSenderId: '541838238652',
    projectId: 'cinefavorite-93f7b',
    storageBucket: 'cinefavorite-93f7b.firebasestorage.app',
    iosBundleId: 'com.example.cinefavorite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-WZLRz4Mw5Eh42QJFG-NmiOIe6kn72bw',
    appId: '1:541838238652:ios:4ec3d80933232e5a4e81b9',
    messagingSenderId: '541838238652',
    projectId: 'cinefavorite-93f7b',
    storageBucket: 'cinefavorite-93f7b.firebasestorage.app',
    iosBundleId: 'com.example.cinefavorite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCks7BKHsleGnaonr8X9Jol5Hk_Gqi7XbU',
    appId: '1:541838238652:web:e6a2099a0257a6b14e81b9',
    messagingSenderId: '541838238652',
    projectId: 'cinefavorite-93f7b',
    authDomain: 'cinefavorite-93f7b.firebaseapp.com',
    storageBucket: 'cinefavorite-93f7b.firebasestorage.app',
    measurementId: 'G-N8N9T8NSPE',
  );
}
